### PR TITLE
Fix reindexing, opportunistic async cleanup

### LINKED ISSUE #84: Reindex broken
Steps to reproduce:
1. Run a reindex in development.

Expected result:
All resources are reindexed.

Actual result:
Amazon_ECS

### PR DESCRIPTION
**Pull request by jmartin-sul**
* **main goal**: fix Crawler logic for parsing `contains` relationships (first commit)
  * new integration test to exercise reindexing, minor tweaks to integration tests to increase max timeout and make tests more re-runnable locally w/o pruning volumes.
  * reflect expected structure in unit test fake.
  * also: the integration tests turn out to exercise both of the `contains` structures that the crawler is coded to parse.  the `/` container, having never been updated by the integration test, has no provenance activity for trellis to return, and so still returns info about contained resources by way of a single flat `'contains'` field directly in the response body.  the `/repository` container, however, has the `'contains'` as a list field in an object in the `'@graph'` list in the response body.
    * the unit tests don't yet exercise the crawler recursion 😞  (wanted to get something up asap, and integration tests seemed like the higher payoff thing to concentrate on)

* _while i'm here..._ tighten up `await` logic and comments for `Crawler.js`, `Indexer.js`, and `Reindexer.js` (second commit)
  * `Indexer.js`: note where `Promise` is returned by function, with expected type for what `Promise` resolves to (instead of conflating function return value/type with resolution value/type of returned `Promise`).
  * `Reindexer.js`: have callback pass along the `Promise` from `this.indexer.index()` as callback return value.
  * `Crawler.js`: `Crawler.request()` should settle iff the `Promise`s it has spawned have settled (`onResource` callback and all recursion through children).  but also, use `Promise.all` to maximize concurrency since callback and child recursion can all happen simultaneously.
  * `Pipeline.integration.js`: no longer need to sleep after call to `Reindexer().reindex()`, since it will only settle when all the operations it has spawned have settled.  update comment explaining why, and how to adjust test if that shifts.

since i worried it might be seen as unnecessary and/or counter to how we actually want to operate, i left the async touchups as a separate (easy to remove) commit.  tests pass for the first commit alone as well as the touchup commit.  still, i think it's an improvement:  the documentation about return types is a little more honest, `reindex()` calls will settle iff all spawned calls have settled (and so a caller can just `await new Reindexer().reindex()` as is done in the integration test), but the regular indexing pipeline still doesn't bother to wait on any of the async calls it spawns (because the error handling already happens in each indexing call, and the pipeline doesn't care beyond firing off the request).  also, the crawler code that coordinates recursion of trellis resources still tries to maximize concurrency by using `Promise.all` to manage the `Promise`s it spawns (as opposed to e.g. looping and `await`ing each one individually).

the second commit was only a couple hours of work, so no huge time investment lost if my thinking turned out to be off base there.

closes #84 (hopefully; also worked for me in my manual testing locally)

### CODE REVIEW

**Comment by jmartin-sul** [comment]
example resource json structures...

old contains structure (may still occur, still supported):
```sh
$ curl -H "Accept: application/ld+json" "http://localhost:8080/" -H 'prefer: return=representation; include="http://www.trellisldp.org/ns/trellis#PreferAudit"' | jq .
```
```json
{
  "@id": "http://platform:8080/",
  "contains": "http://platform:8080/repository",
  "@context": {
    "contains": {
      "@id": "http://www.w3.org/ns/ldp#contains",
      "@type": "@id"
    },
    "schema": "http://schema.org/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "memento": "http://mementoweb.org/ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "acl": "http://www.w3.org/ns/auth/acl#",
    "geo": "http://www.w3.org/2003/01/geo/wgs84_pos#",
    "dc11": "http://purl.org/dc/elements/1.1/",
    "as": "https://www.w3.org/ns/activitystreams#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "ldp": "http://www.w3.org/ns/ldp#",
    "time": "http://www.w3.org/2006/time#",
    "prov": "http://www.w3.org/ns/prov#",
    "dc": "http://purl.org/dc/terms/"
  }
}
```

new contains structure (will be what the majority of recursable containers look like, including `/repository` and its children):
``` sh
$ curl -H "Accept: application/ld+json" "http://localhost:8080/repository" -H 'prefer: return=representation; include="http://www.trellisldp.org/ns/trellis#PreferAudit"' | jq .
```
```json
{
  "@graph": [
    {
      "@id": "_:b0",
      "@type": [
        "prov:Activity",
        "as:Create"
      ],
      "atTime": "2019-10-25T18:46:12.986Z",
      "wasAssociatedWith": "http://www.trellisldp.org/ns/trellis#AnonymousAgent"
    },
    {
      "@id": "http://platform:8080/repository",
      "label": "Sinopia LDP Server",
      "contains": [
        "http://platform:8080/repository/stanford_re_115_2",
        "http://platform:8080/repository/stanford_re_115_3",
        "http://platform:8080/repository/stanford_re_8360_2",
        "http://platform:8080/repository/stanford_re_8360_0",
        "http://platform:8080/repository/stanford_re_5198_0",
        "http://platform:8080/repository/stanford_re_8360_3",
        "http://platform:8080/repository/stanford_re_5198_1"
      ],
      "wasGeneratedBy": "_:b0"
    }
  ],
  "@context": {
    "wasAssociatedWith": {
      "@id": "http://www.w3.org/ns/prov#wasAssociatedWith",
      "@type": "@id"
    },
    "atTime": {
      "@id": "http://www.w3.org/ns/prov#atTime",
      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
    },
    "contains": {
      "@id": "http://www.w3.org/ns/ldp#contains",
      "@type": "@id"
    },
    "label": {
      "@id": "http://www.w3.org/2000/01/rdf-schema#label"
    },
    "wasGeneratedBy": {
      "@id": "http://www.w3.org/ns/prov#wasGeneratedBy",
      "@type": "@id"
    },
    "schema": "http://schema.org/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "memento": "http://mementoweb.org/ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "acl": "http://www.w3.org/ns/auth/acl#",
    "geo": "http://www.w3.org/2003/01/geo/wgs84_pos#",
    "dc11": "http://purl.org/dc/elements/1.1/",
    "as": "https://www.w3.org/ns/activitystreams#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "ldp": "http://www.w3.org/ns/ldp#",
    "time": "http://www.w3.org/2006/time#",
    "prov": "http://www.w3.org/ns/prov#",
    "dc": "http://purl.org/dc/terms/"
  }
}
```

File: src/Crawler.js [hunk 1]
```diff
@@ -45,22 +45,36 @@ export default class Crawler {
...
   toArray(object) {
     return Array.isArray(object) ? object : Array.of(object)
   }
 
+  containedResourcesArray(responseBody) {
+    if (responseBody && responseBody.contains)
+      return this.toArray(responseBody.contains)
+
+    if (responseBody && responseBody['@graph']) {
+      const containsElt = responseBody['@graph'].find((elt) => 'contains' in elt)
```
Comment (mjgiarlo) [inline src/Crawler.js]: What's an elt?

Comment (jmartin-sul) [reply src/Crawler.js]: oh, i dunno how common that abbreviation is, i've seen that as shorthand for element in little anon functions that get applied to lists and such.  similar to `tx` and `transaction` in persistence-related things.

i use that pretty regularly, but am happy to switch if others find it cryptic.

Comment (mjgiarlo) [reply src/Crawler.js]: aha! np, was curious.

File: __tests__/Pipeline.integration.js [hunk 2]
```diff
@@ -128,6 +131,101 @@ describe('integration tests', () => {
...
+            term: {
+              _id: {
+                value: identifier
+              }
+            }
+          }
+        }
+      }).then(response => {
+        // including phrase makes it easier to find the one that fails the test, should the test fail
+        expect([identifier, response.hits.total]).toEqual([identifier, response.hits.total])
```
Comment (mjgiarlo) [inline __tests__/Pipeline.integration.js]: @jmartin-sul I didn't realize until just now that I should have asked: can this test (or the one on line 224) ever fail?

Comment (jmartin-sul) [reply __tests__/Pipeline.integration.js]: d'oh!  good catch @mjgiarlo.  i believe the right hand side of the comparison in both cases should be `1` (since it's doing a specific search for the constructed slug, ```${reindexingResourceSlug}_${i}```, so as not to get thrown off by other things in thing index).

um, file a bug, i guess?  should be a pretty quick fix, unless turning these lines into real tests reveals a bug, but hopefully that won't be the case!

Comment (mjgiarlo) [reply __tests__/Pipeline.integration.js]: I'm already in code nearby so I'll have at it. thank you!

Comment (jmartin-sul) [reply __tests__/Pipeline.integration.js]: nice, np, thank you for spotting that!
